### ISSUE TITLE
Build was failed duo to a newer version of macOS 12.0

### ISSUE THREAD

**Issue by winkee01** [eth-siplab/SVG2Keynote-gui#5]
Build was failed duo to a higer version of macOS
```
Showing Recent Issues
Ld /Users/winkee/Library/Developer/Xcode/DerivedData/KeynoteSVGUI-hcuuipfefrqsddemdrdokfbrizsg/Build/Products/Debug/KeynoteSVGUI.app/Contents/MacOS/KeynoteSVGUI normal (in target 'KeynoteSVGUI' from project 'KeynoteSVGUI')
    cd /Users/winkee/Downloads/SVG2Keynote-gui
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target x86_64-apple-macos10.15 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -L/Users/winkee/Library/Developer/Xcode/DerivedData/KeynoteSVGUI-hcuuipfefrqsddemdrdokfbrizsg/Build/Products/Debug -L/Users/winkee/Downloads/SVG2Keynote-gui -L/usr/local/lib -F/Users/winkee/Library/Developer/Xcode/DerivedData/KeynoteSVGUI-hcuuipfefrqsddemdrdokfbrizsg/Build/Products/Debug/PackageFrameworks -F/Users/winkee/Library/Developer/Xcode/DerivedData/KeynoteSVGUI-hcuuipfefrqsddemdrdokfbrizsg/Build/Products/Debug -filelist /Users/winkee/Library/Developer/Xcode/DerivedData/KeynoteSVGUI-hcuuipfefrqsddemdrdokfbrizsg/Build/Intermediates.noindex/KeynoteSVGUI.build/Debug/KeynoteSVGUI.build/Objects-normal/x86_64/KeynoteSVGUI.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/../Frameworks -Xlinker -object_path_lto -Xlinker /Users/winkee/Library/Developer/Xcode/DerivedData/KeynoteSVGUI-hcuuipfefrqsddemdrdokfbrizsg/Build/Intermediates.noindex/KeynoteSVGUI.build/Debug/KeynoteSVGUI.build/Objects-normal/x86_64/KeynoteSVGUI_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -stdlib\=libc++ -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/winkee/Library/Developer/Xcode/DerivedData/KeynoteSVGUI-hcuuipfefrqsddemdrdokfbrizsg/Build/Intermediates.noindex/KeynoteSVGUI.build/Debug/KeynoteSVGUI.build/Objects-normal/x86_64/KeynoteSVGUI.swiftmodule -lprotobuf -lsnappy -lkeynote_lib -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/winkee/Library/Developer/Xcode/DerivedData/KeynoteSVGUI-hcuuipfefrqsddemdrdokfbrizsg/Build/Intermediates.noindex/KeynoteSVGUI.build/Debug/KeynoteSVGUI.build/Objects-normal/x86_64/KeynoteSVGUI_dependency_info.dat -o /Users/winkee/Library/Developer/Xcode/DerivedData/KeynoteSVGUI-hcuuipfefrqsddemdrdokfbrizsg/Build/Products/Debug/KeynoteSVGUI.app/Contents/MacOS/KeynoteSVGUI -Xlinker -add_ast_path -Xlinker /Users/winkee/Library/Developer/Xcode/DerivedData/KeynoteSVGUI-hcuuipfefrqsddemdrdokfbrizsg/Build/Intermediates.noindex/SVGWebView.build/Debug/SVGWebView.build/Objects-normal/x86_64/SVGWebView.swiftmodule

ld: warning: dylib (/usr/local/lib/libprotobuf.dylib) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(keynote.cpp.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(proto_helper.cpp.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(key_to_svg.cpp.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(svg_to_key.cpp.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(common_message_creation.cpp.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(snappy_helper.cpp.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(nanosvg_helper.cpp.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(shape_creation_repository.cpp.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(svg_wrapper.cpp.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(ProtoMapping.cpp.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(SlideObjectFactory.cpp.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(KNArchives.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSDArchives.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSPArchiveMessages.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSPMessages.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSSArchives.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSWPArchives.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(nanosvg_impl.cpp.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(ShapeObject.cpp.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(SlideObject.cpp.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(KNCommandArchives.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSAArchives.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSDCommandArchives.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSKArchives.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSTArchives.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSTCommandArchives.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSTStylePropertyArchiving.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSCEArchives.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSCHArchives.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSCHArchives.Common.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSCHCommandArchives.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSCHPreUFFArchives.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSWPCommandArchives.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(KNCommandArchives.sos.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSACommandArchives.sos.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSKArchives.sos.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libsnappy.a(snappy.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSWPArchives.sos.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(BaseObject.cpp.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSCH3DArchives.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSCHArchives.GEN.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSAArchives.sos.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSDArchives.sos.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSSArchives.sos.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libkeynote_lib.a(TSTArchives.sos.pb.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
ld: warning: object file (/Users/winkee/Downloads/SVG2Keynote-gui/libsnappy.a(snappy-sinksource.cc.o)) was built for newer macOS version (11.0) than being linked (10.15)
Undefined symbols for architecture x86_64:
  "google::protobuf::internal::ExtensionSet::MergeFrom(google::protobuf::internal::ExtensionSet const&)", referenced from:
      TSD::FillArchive::FillArchive(TSD::FillArchive const&) in libkeynote_lib.a(TSDArchives.pb.cc.o)
      TSD::FillArchive::MergeFrom(TSD::FillArchive const&) in libkeynote_lib.a(TSDArchives.pb.cc.o)
      TSD::GroupArchive::GroupArchive(TSD::GroupArchive const&) in libkeynote_lib.a(TSDArchives.pb.cc.o)
      TSD::GroupArchive::MergeFrom(TSD::GroupArchive const&) in libkeynote_lib.a(TSDArchives.pb.cc.o)
      TSD::ImageArchive::ImageArchive(TSD::ImageArchive const&) in libkeynote_lib.a(TSDArchives.pb.cc.o)
      TSD::ImageArchive::MergeFrom(TSD::ImageArchive const&) in libkeynote_lib.a(TSDArchives.pb.cc.o)
      TSP::DataAttributes::DataAttributes(TSP::DataAttributes const&) in libkeynote_lib.a(TSPMessages.pb.cc.o)
      ...
  "google::protobuf::internal::ExtensionSet::_InternalSerializeImpl(int, int, unsigned char*, google::protobuf::io::EpsCopyOutputStream*) const", referenced from:
      TSD::FillArchive::_InternalSerialize(unsigned char*, google::protobuf::io::EpsCopyOutputStream*) const in libkeynote_lib.a(TSDArchives.pb.cc.o)
      TSD::GroupArchive::_InternalSerialize(unsigned char*, google::protobuf::io::EpsCopyOutputStream*) const in libkeynote_lib.a(TSDArchives.pb.cc.o)
      TSD::ImageArchive::_InternalSerialize(unsigned char*, google::protobuf::io::EpsCopyOutputStream*) const in libkeynote_lib.a(TSDArchives.pb.cc.o)
      TSP::DataAttributes::_InternalSerialize(unsigned char*, google::protobuf::io::EpsCopyOutputStream*) const in libkeynote_lib.a(TSPMessages.pb.cc.o)
      TSS::ThemeArchive::_InternalSerialize(unsigned char*, google::protobuf::io::EpsCopyOutputStream*) const in libkeynote_lib.a(TSSArchives.pb.cc.o)
      TSS::CommandPropertyEntryArchive::_InternalSerialize(unsigned char*, google::protobuf::io::EpsCopyOutputStream*) const in libkeynote_lib.a(TSSArchives.pb.cc.o)
      TSK::FormatStructArchive::_InternalSerialize(unsigned char*, google::protobuf::io::EpsCopyOutputStream*) const in libkeynote_lib.a(TSKArchives.pb.cc.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by winkee01** [comment]
solved by rebuilding `libkeynote_lib.a` in my environment.

**Comment by kosuvorov** [comment]
Hi, could you help me please? I have a problem "Build input file cannot be found". How can I solve this problem?

**Comment by kosuvorov** [comment]
@winkee01 
Also how can I rebuild libkeynote_lib.a in my environment? And should I do this after all? I'm not a developer, so I'm totally green in this.

**Comment by winkee01** [comment]
@kostua-xd you can follow this step:

```
brew install boost
brew install protobuf
git clone --recurse-submodules https://github.com/eth-siplab/SVG2Keynote-lib
cd SVG2Keynote-lib
cmake -H. -Bbuild -DBoost_NO_BOOST_CMAKE=ON
make -C build
```

After success, you replace `libkeynote_lib.a` with your newly built one.

**Comment by kosuvorov** [comment]
Thank you for helping me. I have got "fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated." doing "make -C build". Do you maybe know why?

**Comment by winkee01** [comment]
what errors? post the details

**Comment by kosuvorov** [comment]
kanstantsinsuvorau@macbook-pro SVG2Keynote-lib % make -C build
Consolidate compiler generated dependencies of target keynote_lib
[  1%] Building CXX object keynote_lib/CMakeFiles/keynote_lib.dir/proto_helper.cpp.o
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/proto_helper.cpp:7:
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/mapping/ProtoMapping.h:8:
/Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/KNArchives.pb.h:17:2: error: This file was generated by an older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
/Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/KNArchives.pb.h:18:2: error: incompatible with your Protocol Buffer headers. Please
#error incompatible with your Protocol Buffer headers. Please
 ^
/Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/KNArchives.pb.h:19:2: error: regenerate this file with a newer version of protoc.
#error regenerate this file with a newer version of protoc.
 ^
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/proto_helper.cpp:7:
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/mapping/ProtoMapping.h:8:
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/KNArchives.pb.h:35:
/Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/TSPMessages.pb.h:17:2: error: This file was generated by an older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
/Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/TSPMessages.pb.h:18:2: error: incompatible with your Protocol Buffer headers. Please
#error incompatible with your Protocol Buffer headers. Please
 ^
/Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/TSPMessages.pb.h:19:2: error: regenerate this file with a newer version of protoc.
#error regenerate this file with a newer version of protoc.
 ^
/Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/TSPMessages.pb.h:409:33: error: non-virtual member function marked 'final' hides virtual member function
  inline Reference* New() const final {
                                ^
/opt/homebrew/include/google/protobuf/message.h:251:12: note: hidden overloaded virtual function 'google::protobuf::Message::New' declared here: different number of parameters (1 vs 0)
  Message* New(Arena* arena) const override = 0;
           ^
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/proto_helper.cpp:7:
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/mapping/ProtoMapping.h:8:
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/KNArchives.pb.h:35:
/Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/TSPMessages.pb.h:590:37: error: non-virtual member function marked 'final' hides virtual member function
  inline DataReference* New() const final {
                                    ^
/opt/homebrew/include/google/protobuf/message.h:251:12: note: hidden overloaded virtual function 'google::protobuf::Message::New' declared here: different number of parameters (1 vs 0)
  Message* New(Arena* arena) const override = 0;
           ^
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/proto_helper.cpp:7:
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/mapping/ProtoMapping.h:8:
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/KNArchives.pb.h:35:
/Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/TSPMessages.pb.h:741:50: error: non-virtual member function marked 'final' hides virtual member function
  inline SparseReferenceArray_Entry* New() const final {
                                                 ^
/opt/homebrew/include/google/protobuf/message.h:251:12: note: hidden overloaded virtual function 'google::protobuf::Message::New' declared here: different number of parameters (1 vs 0)
  Message* New(Arena* arena) const override = 0;
           ^
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/proto_helper.cpp:7:
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/mapping/ProtoMapping.h:8:
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/KNArchives.pb.h:35:
/Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/TSPMessages.pb.h:801:3: error: use of undeclared identifier 'PROTOBUF_MUST_USE_RESULT'
  PROTOBUF_MUST_USE_RESULT ::TSP::Reference* release_reference();
  ^
/Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/TSPMessages.pb.h:915:44: error: non-virtual member function marked 'final' hides virtual member function
  inline SparseReferenceArray* New() const final {
                                           ^
/opt/homebrew/include/google/protobuf/message.h:251:12: note: hidden overloaded virtual function 'google::protobuf::Message::New' declared here: different number of parameters (1 vs 0)
  Message* New(Arena* arena) const override = 0;
           ^
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/proto_helper.cpp:7:
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/mapping/ProtoMapping.h:8:
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/KNArchives.pb.h:35:
/Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/TSPMessages.pb.h:1088:29: error: non-virtual member function marked 'final' hides virtual member function
  inline Point* New() const final {
                            ^
/opt/homebrew/include/google/protobuf/message.h:251:12: note: hidden overloaded virtual function 'google::protobuf::Message::New' declared here: different number of parameters (1 vs 0)
  Message* New(Arena* arena) const override = 0;
           ^
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/proto_helper.cpp:7:
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/mapping/ProtoMapping.h:8:
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/KNArchives.pb.h:35:
/Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/TSPMessages.pb.h:1257:28: error: non-virtual member function marked 'final' hides virtual member function
  inline Size* New() const final {
                           ^
/opt/homebrew/include/google/protobuf/message.h:251:12: note: hidden overloaded virtual function 'google::protobuf::Message::New' declared here: different number of parameters (1 vs 0)
  Message* New(Arena* arena) const override = 0;
           ^
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/proto_helper.cpp:7:
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/mapping/ProtoMapping.h:8:
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/KNArchives.pb.h:35:
/Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/TSPMessages.pb.h:1426:29: error: non-virtual member function marked 'final' hides virtual member function
  inline Range* New() const final {
                            ^
/opt/homebrew/include/google/protobuf/message.h:251:12: note: hidden overloaded virtual function 'google::protobuf::Message::New' declared here: different number of parameters (1 vs 0)
  Message* New(Arena* arena) const override = 0;
           ^
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/proto_helper.cpp:7:
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/mapping/ProtoMapping.h:8:
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/KNArchives.pb.h:35:
/Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/TSPMessages.pb.h:1595:28: error: non-virtual member function marked 'final' hides virtual member function
  inline Date* New() const final {
                           ^
/opt/homebrew/include/google/protobuf/message.h:251:12: note: hidden overloaded virtual function 'google::protobuf::Message::New' declared here: different number of parameters (1 vs 0)
  Message* New(Arena* arena) const override = 0;
           ^
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/proto_helper.cpp:7:
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/mapping/ProtoMapping.h:8:
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/KNArchives.pb.h:35:
/Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/TSPMessages.pb.h:1746:32: error: non-virtual member function marked 'final' hides virtual member function
  inline IndexSet* New() const final {
                               ^
/opt/homebrew/include/google/protobuf/message.h:251:12: note: hidden overloaded virtual function 'google::protobuf::Message::New' declared here: different number of parameters (1 vs 0)
  Message* New(Arena* arena) const override = 0;
           ^
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/proto_helper.cpp:7:
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/mapping/ProtoMapping.h:8:
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/KNArchives.pb.h:35:
/Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/TSPMessages.pb.h:1901:29: error: non-virtual member function marked 'final' hides virtual member function
  inline Color* New() const final {
                            ^
/opt/homebrew/include/google/protobuf/message.h:251:12: note: hidden overloaded virtual function 'google::protobuf::Message::New' declared here: different number of parameters (1 vs 0)
  Message* New(Arena* arena) const override = 0;
           ^
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/proto_helper.cpp:7:
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/mapping/ProtoMapping.h:8:
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/KNArchives.pb.h:35:
/Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/TSPMessages.pb.h:2264:36: error: non-virtual member function marked 'final' hides virtual member function
  inline Path_Element* New() const final {
                                   ^
/opt/homebrew/include/google/protobuf/message.h:251:12: note: hidden overloaded virtual function 'google::protobuf::Message::New' declared here: different number of parameters (1 vs 0)
  Message* New(Arena* arena) const override = 0;
           ^
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/proto_helper.cpp:7:
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/mapping/ProtoMapping.h:8:
In file included from /Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/KNArchives.pb.h:35:
/Users/kanstantsinsuvorau/SVG2Keynote-lib/keynote_lib/../keynote-protos/gen/TSPMessages.pb.h:2435:28: error: non-virtual member function marked 'final' hides virtual member function
  inline Path* New() const final {
                           ^
/opt/homebrew/include/google/protobuf/message.h:251:12: note: hidden overloaded virtual function 'google::protobuf::Message::New' declared here: different number of parameters (1 vs 0)
  Message* New(Arena* arena) const override = 0;
           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [keynote_lib/CMakeFiles/keynote_lib.dir/proto_helper.cpp.o] Error 1
make[1]: *** [keynote_lib/CMakeFiles/keynote_lib.dir/all] Error 2
make: *** [all] Error 2


These errors 😅

**Comment by winkee01** [comment]
you also have to rebuild `proto-dump`, it's a binary executable application.
![image](https://user-images.githubusercontent.com/49930785/161377105-e633ecfd-55eb-402c-8106-3b1f5cb7d075.png)

Follow the below instructions:

**1) clone proto-dump repo**
```
git clone --recurse-submodules https://github.com/obriensp/proto-dump
```

**2) compile proto-dump source to get the binary app**
use **xcode** to open `.proto-dump.xcodeproj` project file, and compile. 
After success, you replace the old one with it.

**3) execute get-protos.sh**
`get-protos.sh` is a bash script, executing it will generate the necessary files for you, which is shown in your error messages.

**4)** make -C build
